package entity;
// Generated 10-Jun-2018 14:49:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvu generated by hbm2java
 */
@Entity
@Table(name="chucvu"
    ,catalog="mob104"
)
public class Chucvu  implements java.io.Serializable {


     private String maChucVu;
     private String tenChucVu;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

    public Chucvu() {
    }

	
    public Chucvu(String maChucVu, String tenChucVu) {
        this.maChucVu = maChucVu;
        this.tenChucVu = tenChucVu;
    }
    public Chucvu(String maChucVu, String tenChucVu, Set<Nhanvien> nhanviens) {
       this.maChucVu = maChucVu;
       this.tenChucVu = tenChucVu;
       this.nhanviens = nhanviens;
    }
   
     @Id 

    
    @Column(name="maChucVu", unique=true, nullable=false, length=10)
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }

    
    @Column(name="tenChucVu", nullable=false, length=50)
    public String getTenChucVu() {
        return this.tenChucVu;
    }
    
    public void setTenChucVu(String tenChucVu) {
        this.tenChucVu = tenChucVu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chucvu")
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }




}


