package entity;
// Generated 10-Jun-2018 14:49:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name="khachhang"
    ,catalog="mob104"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="soDienThoai")} 
)
public class Khachhang  implements java.io.Serializable {


     private Integer maKhachHang;
     private String tenKhachHang;
     private String diaChi;
     private String anhDaiDien;
     private String soDienThoai;
     private String email;
     private String matKhau;
     private Set<Donhang> donhangs = new HashSet<Donhang>(0);

    public Khachhang() {
    }

	
    public Khachhang(String tenKhachHang, String diaChi, String matKhau) {
        this.tenKhachHang = tenKhachHang;
        this.diaChi = diaChi;
        this.matKhau = matKhau;
    }
    public Khachhang(String tenKhachHang, String diaChi, String anhDaiDien, String soDienThoai, String email, String matKhau, Set<Donhang> donhangs) {
       this.tenKhachHang = tenKhachHang;
       this.diaChi = diaChi;
       this.anhDaiDien = anhDaiDien;
       this.soDienThoai = soDienThoai;
       this.email = email;
       this.matKhau = matKhau;
       this.donhangs = donhangs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="maKhachHang", unique=true, nullable=false)
    public Integer getMaKhachHang() {
        return this.maKhachHang;
    }
    
    public void setMaKhachHang(Integer maKhachHang) {
        this.maKhachHang = maKhachHang;
    }

    
    @Column(name="tenKhachHang", nullable=false, length=200)
    public String getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(String tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }

    
    @Column(name="diaChi", nullable=false, length=300)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="anhDaiDien", length=50)
    public String getAnhDaiDien() {
        return this.anhDaiDien;
    }
    
    public void setAnhDaiDien(String anhDaiDien) {
        this.anhDaiDien = anhDaiDien;
    }

    
    @Column(name="soDienThoai", unique=true, length=12)
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    
    @Column(name="email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="matKhau", nullable=false, length=50)
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khachhang")
    public Set<Donhang> getDonhangs() {
        return this.donhangs;
    }
    
    public void setDonhangs(Set<Donhang> donhangs) {
        this.donhangs = donhangs;
    }




}


