package entity;
// Generated 10-Jun-2018 14:49:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name="nhanvien"
    ,catalog="mob104"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cmnd"), @UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="soDienThoai")} 
)
public class Nhanvien  implements java.io.Serializable {


     private String maNhanVien;
     private Chucvu chucvu;
     private String tenNhanVien;
     private String email;
     private String anhDaiDien;
     private String soDienThoai;
     private String diaChi;
     private String cmnd;
     private Float luongCoBan;
     private Set<Tinhtrangdonhang> tinhtrangdonhangs = new HashSet<Tinhtrangdonhang>(0);

    public Nhanvien() {
    }

	
    public Nhanvien(String maNhanVien, String tenNhanVien, String diaChi, String cmnd) {
        this.maNhanVien = maNhanVien;
        this.tenNhanVien = tenNhanVien;
        this.diaChi = diaChi;
        this.cmnd = cmnd;
    }
    public Nhanvien(String maNhanVien, Chucvu chucvu, String tenNhanVien, String email, String anhDaiDien, String soDienThoai, String diaChi, String cmnd, Float luongCoBan, Set<Tinhtrangdonhang> tinhtrangdonhangs) {
       this.maNhanVien = maNhanVien;
       this.chucvu = chucvu;
       this.tenNhanVien = tenNhanVien;
       this.email = email;
       this.anhDaiDien = anhDaiDien;
       this.soDienThoai = soDienThoai;
       this.diaChi = diaChi;
       this.cmnd = cmnd;
       this.luongCoBan = luongCoBan;
       this.tinhtrangdonhangs = tinhtrangdonhangs;
    }
   
     @Id 

    
    @Column(name="maNhanVien", unique=true, nullable=false, length=10)
    public String getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maChucVu")
    public Chucvu getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Chucvu chucvu) {
        this.chucvu = chucvu;
    }

    
    @Column(name="tenNhanVien", nullable=false, length=150)
    public String getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(String tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }

    
    @Column(name="email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="anhDaiDien", length=50)
    public String getAnhDaiDien() {
        return this.anhDaiDien;
    }
    
    public void setAnhDaiDien(String anhDaiDien) {
        this.anhDaiDien = anhDaiDien;
    }

    
    @Column(name="soDienThoai", unique=true, length=12)
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    
    @Column(name="diaChi", nullable=false, length=300)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="cmnd", unique=true, nullable=false, length=11)
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    
    @Column(name="luongCoBan", precision=12, scale=0)
    public Float getLuongCoBan() {
        return this.luongCoBan;
    }
    
    public void setLuongCoBan(Float luongCoBan) {
        this.luongCoBan = luongCoBan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Tinhtrangdonhang> getTinhtrangdonhangs() {
        return this.tinhtrangdonhangs;
    }
    
    public void setTinhtrangdonhangs(Set<Tinhtrangdonhang> tinhtrangdonhangs) {
        this.tinhtrangdonhangs = tinhtrangdonhangs;
    }




}


