package entity;
// Generated 10-Jun-2018 14:49:30 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tinhtrangdonhang generated by hbm2java
 */
@Entity
@Table(name="tinhtrangdonhang"
    ,catalog="mob104"
)
public class Tinhtrangdonhang  implements java.io.Serializable {


     private Integer id;
     private Donhang donhang;
     private Nhanvien nhanvien;
     private Trangthai trangthai;
     private Date thoiGian;

    public Tinhtrangdonhang() {
    }

    public Tinhtrangdonhang(Donhang donhang, Nhanvien nhanvien, Trangthai trangthai, Date thoiGian) {
       this.donhang = donhang;
       this.nhanvien = nhanvien;
       this.trangthai = trangthai;
       this.thoiGian = thoiGian;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maDonHang")
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maNhanVien")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maTrangThai")
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="thoiGian", length=10)
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }




}


