package entity;
// Generated 10-Jun-2018 14:49:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trangthai generated by hbm2java
 */
@Entity
@Table(name="trangthai"
    ,catalog="mob104"
)
public class Trangthai  implements java.io.Serializable {


     private String maTrangThai;
     private String trangThai;
     private Set<Tinhtrangdonhang> tinhtrangdonhangs = new HashSet<Tinhtrangdonhang>(0);

    public Trangthai() {
    }

	
    public Trangthai(String maTrangThai, String trangThai) {
        this.maTrangThai = maTrangThai;
        this.trangThai = trangThai;
    }
    public Trangthai(String maTrangThai, String trangThai, Set<Tinhtrangdonhang> tinhtrangdonhangs) {
       this.maTrangThai = maTrangThai;
       this.trangThai = trangThai;
       this.tinhtrangdonhangs = tinhtrangdonhangs;
    }
   
     @Id 

    
    @Column(name="maTrangThai", unique=true, nullable=false, length=10)
    public String getMaTrangThai() {
        return this.maTrangThai;
    }
    
    public void setMaTrangThai(String maTrangThai) {
        this.maTrangThai = maTrangThai;
    }

    
    @Column(name="trangThai", nullable=false, length=200)
    public String getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trangthai")
    public Set<Tinhtrangdonhang> getTinhtrangdonhangs() {
        return this.tinhtrangdonhangs;
    }
    
    public void setTinhtrangdonhangs(Set<Tinhtrangdonhang> tinhtrangdonhangs) {
        this.tinhtrangdonhangs = tinhtrangdonhangs;
    }




}


